spring.application.name=FakeBook

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/fakebook}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123456}

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=2

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

signer_key=${SIGNER_KEY:default_signer_key}
username_admin=${USERNAME_ADMIN:admin}
password_admin=${PASSWORD_ADMIN:admin@123}
email_admin=${EMAIL_ADMIN:admin@gmail.com}

logging.level.root=INFO
logging.level.com.example.todoApp.service=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG