spring.application.name=FakeBook

spring.datasource.url= ${DATABASE_URL}
spring.datasource.username= ${DATABASE_USERNAME}
spring.datasource.password= ${DATABASE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=2

spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
server.port = 8080

signer_key = ${SIGNER_KEY}
username_admin = ${USERNAME_ADMIN}
password_admin = ${PASSWORD_ADMIN}
email_admin = ${EMAIL_ADMIN}

logging.level.root=INFO
logging.level.com.example.todoApp.service=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG

#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.timeout=2000